/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_espeakng_jeditor_jni_ESpeakService */

#ifndef _Included_org_espeakng_jeditor_jni_ESpeakService
#define _Included_org_espeakng_jeditor_jni_ESpeakService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_espeakng_jeditor_jni_ESpeakService
 * Method:    nativeSpeak
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_espeakng_jeditor_jni_ESpeakService_nativeSpeak
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_espeakng_jeditor_jni_ESpeakService
 * Method:    nativeGetPhonemeList
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_espeakng_jeditor_jni_ESpeakService_nativeGetPhonemeList
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_espeakng_jeditor_jni_ESpeakService
 * Method:    nativeGetEspeakNgVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_espeakng_jeditor_jni_ESpeakService_nativeGetEspeakNgVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_espeakng_jeditor_jni_ESpeakService
 * Method:    nativeGetSpectSeq
 * Signature: (Lorg/espeakng/jeditor/jni/SpectSeq;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_espeakng_jeditor_jni_ESpeakService_nativeGetSpectSeq
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     org_espeakng_jeditor_jni_ESpeakService
 * Method:    nativeTextToPhonemes
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_espeakng_jeditor_jni_ESpeakService_nativeTextToPhonemes
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
