/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eSpeakServices_ESpeakService */

#ifndef _Included_eSpeakServices_ESpeakService
#define _Included_eSpeakServices_ESpeakService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eSpeakServices_ESpeakService
 * Method:    nativeGetEspeakNgVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eSpeakServices_ESpeakService_nativeGetEspeakNgVersion
  (JNIEnv *, jclass);

/*
 * Class:     eSpeakServices_ESpeakService
 * Method:    nativeGetSpectSeq
 * Signature: (LdataStructure/eSpeakStructure/SpectSeq;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eSpeakServices_ESpeakService_nativeGetSpectSeq
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
