/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ESpeakService */

#ifndef _Included_ESpeakService
#define _Included_ESpeakService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ESpeakService
 * Method:    getEspeakNgVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ESpeakService_getEspeakNgVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
